apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhellad-app
  namespace: dev
spec:
  selector:
    matchLabels:
      app: akhellad-app
  replicas: 1
  template:
    metadata:
      labels:
        app: akhellad-app
    spec:
      containers:
      - name: akhellad-app
        image: akhelld/iot-app-akhellad:v2
        ports:
        - containerPort: 8888
