apiVersion: v1
kind: Service
metadata:
  name: akhellad-app-service
  namespace: dev
spec:
  selector:
    app: akhellad-app
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
  type: ClusterIP

